AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Resources:
  HelloFunction:
    # This resource creates a Lambda function.
    Type: 'AWS::Serverless::Function'

    Properties:

      # This function uses the Nodejs v6.10 runtime.
      Runtime: nodejs6.10

      # This is the Lambda function's handler.
      Handler: 'src/hello.handler'

      # Event sources to attach to this function. In this case, we are attaching
      # one API Gateway endpoint to the Lambda function. The function is
      # called when a HTTP request is made to the API Gateway endpoint.
      Events:

        HelloApi:
          # Define an API Gateway endpoint that responds to HTTP GET at /hello
          Type: Api
          Properties:
            Path: /hello
            Method: GET